[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Explicitly set the filesystem to SPIFFS
board_build.filesystem = spiffs

; Automatically download the required libraries
lib_deps = 
	sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library @ ^1.0.4
	paulstoffregen/OneWire @ ^2.3.8
	milesburton/DallasTemperature @ ^3.11.0
	adafruit/Adafruit GFX Library @ ^1.11.9
	adafruit/Adafruit SSD1306 @ ^2.5.9